resolver: https://raw.githubusercontent.com/EdutainmentLIVE/snapshot/d3fc895f40d93214fa8d9def7cc32f19329a6c0c/snapshot.yaml
extra-deps:
  - brittany-0.13.1.0
  - data-tree-print-0.1.0.2
  - dir-traverse-0.2.3.0
  - hasktags-0.71.2
  - json-0.10
  - microaeson-0.1.0.0
  - trial-tomland-0.0.0.0
  - weeder-2.1.3

  # https://github.com/kowainik/colourista/pull/46
  - git: https://github.com/kowainik/colourista
    commit: c73154cd46c44fa710f4ae2d21c3fbacf65b8007

  # https://github.com/kowainik/extensions/pull/66
  - git: https://github.com/kowainik/extensions
    commit: 8c9510e8072e477561b2406136ddd375795501bf

  # https://github.com/kowainik/stan/pull/398
  - git: https://github.com/kowainik/stan
    commit: 86977865db1cd2e46985fc5e787d84cb880e0af4

  # https://github.com/jaspervdj/stylish-haskell/pull/336
  - git: https://github.com/jaspervdj/stylish-haskell
    commit: 8f8034c833a93f2dc8d0fc0a9a6f8806fbc1766e

  # https://github.com/kowainik/trial/pull/63
  - git: https://github.com/kowainik/trial
    commit: 1126f99749ae20ceb11df7750955b548e01b130a
    subdirs:
      - trial
      - trial-optparse-applicative
